apps/add_object/urls.py
from django.urls import path, re_path, include
from apps.add_object import views as add_views


urlpatterns = [
    path(r'^$', add_views.add_object, name='add_object'),
]
# не договор а контракт? бренд перед подрядчиком
# адрес, контакты, кто инжинер, законченный, 

apps/core/urls.py
from django.urls import path, re_path, include
from apps.core import views as core_views


urlpatterns = [
    path('', core_views.home_page, name='home'),
    re_path(r'^(?P<slug>[-\w]+)/$', core_views.project_detail, name='project_detail'),
    path('accounts/', include('django.contrib.auth.urls')),
]

settings/urls.py
# from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.core.urls', 'core'), namespace='core')),
    path(r'^add/',  include(('apps.add_object.urls', 'add_object'), namespace='add_object'))
]

apps/add_object/models.py
from django.db import models
from apps.core.models import Project


class Project1(models.Model):
    FINISHED = 'Закончен'
    INWORK = 'В работе'
    STATUS_CHOICES = ((FINISHED, "Закончен"),
    (INWORK, "В работе"))

    name = models.CharField(max_length=200, db_index=True, verbose_name=u'Название проекта')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    contract_number = models.IntegerField(db_index=True, unique=True, verbose_name=u'Номер контракта')
    brand = models.CharField(max_length=200, db_index=True, verbose_name=u'Бренд')
    contractor = models.CharField(max_length=200, db_index=True, verbose_name=u'Подрядчик')
    contractor_contract = models.IntegerField(db_index=True, unique=True, verbose_name=u'Номер договора с подрядчиком')
    advance_payment1 = models.CharField(max_length=200, verbose_name=u'Аванс')
    advance_payment2 = models.CharField(max_length=200, verbose_name=u'Аванс')
    advance_payment3 = models.CharField(max_length=200, verbose_name=u'Аванс')
    final_sum = models.CharField(max_length=200, verbose_name=u'Итоговая сумма')
    cs_upd = models.CharField(max_length=200, verbose_name=u'КС/УПД')
    adress = models.CharField(max_length=200, verbose_name=u'Адрес')
    contacts = models.CharField(max_length=200, verbose_name=u'Контакты')
    engineer = models.CharField(max_length=200, verbose_name=u'Инженер')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=INWORK, verbose_name=u'Статус')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'

    def __str__(self):
        return self.name

apps/core/models.py
from asyncio.base_futures import _FINISHED
from django.db import models
from django.shortcuts import reverse

class Project(models.Model):
    FINISHED = 'Закончен'
    INWORK = 'В работе'
    STATUS_CHOICES = ((FINISHED, "Закончен"),
    (INWORK, "В работе"))

    name = models.CharField(max_length=200, db_index=True, verbose_name='Название проекта')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)
    contract_number = models.IntegerField(db_index=True, unique=True, verbose_name='Номер контракта')
    brand = models.CharField(max_length=200, db_index=True, verbose_name='Бренд')
    contractor = models.CharField(max_length=200, db_index=True, verbose_name='Подрядчик')
    contractor_contract = models.IntegerField(db_index=True, unique=True, verbose_name='Номер договора с подрядчиком')
    advance_payment1 = models.CharField(max_length=200, verbose_name='Аванс')
    advance_payment2 = models.CharField(max_length=200, verbose_name='Аванс')
    advance_payment3 = models.CharField(max_length=200, verbose_name='Аванс')
    final_sum = models.CharField(max_length=200, verbose_name='Итоговая сумма')
    cs_upd = models.CharField(max_length=200, verbose_name='КС/УПД')
    adress = models.CharField(max_length=200, verbose_name='Адрес')
    contacts = models.CharField(max_length=200, verbose_name='Контакты')
    engineer = models.CharField(max_length=200, verbose_name='Инженер')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=INWORK, verbose_name='Статус')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('core:project_detail', kwargs={"slug" : self.slug})

apps/add_object/forms.py
from django import forms
from django.utils.text import slugify
from apps.core.models import Project

class ProjectCreateForm(forms.ModelForm):
    # slug = forms.CharField(widget=forms.TextInput(attrs={slugify('name', allow_unicode=True) :'number_out'}))
    class Meta:
        model = Project
        fields = ['name', 'slug', 'contract_number', 'brand', 'contractor', 'contractor_contract', 'advance_payment1',
                'advance_payment2', 'advance_payment3', 'final_sum', 'cs_upd', 'adress', 'contacts', 'engineer', 'status']

apps/core/forms.py
from django import forms, models

apps/add_object/views.py
from django.shortcuts import render
from apps.core.models import Project
from .forms import ProjectCreateForm

def add_object(request):
    if request.method == 'POST':
        form = ProjectCreateForm(request.POST)
        if form.is_valid():
            project = form.save()
            return render(request, 'add_object/added.html', {'project': project})
    
    else:
        form = ProjectCreateForm
    return render(request, 'add_object/add.html', {'form': form})
    

apps/core/views.py
from re import template
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.contrib.auth import authenticate, login
from django.views.generic import TemplateView
from apps.core.models import Project

def home_page(request):
    projects = Project.objects.all()

    return render(
            request,
            'core/db.html',
            {'projects': projects}
        )

def project_detail(request, slug):
    project = get_object_or_404(Project, slug=slug)

    return render(
            request,
            'core/detail.html',
            {'project': project}
        )


    

apps/add_object/templates/add_object/add.html
{% extends "base.html" %}
{% block title %}
Новый проект
{% endblock %}
{% block content %}
<div class="container-fluid content">
    <button type="button" value="Previous Page" class="btn btn-dark" onClick="window.history.back();return false;" style="margin-left: 6%; margin-top: 3%;">
        Назад
    </button>
    <div class="col-md-6" style="margin-left: 25%; margin-bottom: 2%;">
        <form action="." method="post">
            <h4>Заполните данные:</h4>
            <div class="col-sm-3">
                {{ form.as_p }}
            </div>
                <input type="submit" class="btn btn-dark" value="Добавить новый проект" style="margin-left: 70%;">
                {% csrf_token %}
        </form>
        
    </div>
</div>
{% endblock %}

apps/add_object/templates/add_object/added.html
{% extends "base.html" %}

{% block title %}Спасибо за покупку{% endblock %}

{% block content %}
<div class="container content" style="margin-top: 6%;">
    <h1>Проект создан</h1>    
    <a href="{% url "core:home" %}" class="btn btn-dark btn-lg">На главную</a>
</div>
{% endblock %}

apps/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Stroi-market{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="font-size: larger;">
        <a class="navbar-brand" href="/">Главная</a>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Log-in</a>
                </li>
                <li class="nav-item">
                    
                </li>
            </ul>
            

        </div>
    </nav>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <footer>
        <div id="privacy">
        </div>
    </footer>
</body>
</html>

apps/core/templates/core/db.html
{% extends  'base.html' %}
{% block title %}
Строй-маркет
{% endblock %}
{% block content %}

<div class="container-fluid content">
    <div class="row">
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th>Название</th>
                <th>Номер договора</th>
                <th>Бренд</th>
                <th>Подрядчик</th>
                <th>Номер договора с подрядчиком</th>
                <th>Статус проекта</th>
                <th>Аванс</th>
                <th>Аванс</th>
                <th>Аванс</th>
                <th>Итоговая сумма</th>
                <th>КС/УПД</th>
            </tr>
            </thead>
            <tbody>
            {% for p in projects %}
                {% if p.status == 'В работе' %}
                    <tr>
                        <td><a href="{{ p.get_absolute_url }}" class="link-warning">{{ p.name }}</a></td>
                        <td>{{ p.contract_number }}</td>
                        <td>{{ p.brand }}</td>
                        <td>{{ p.contractor }}</td>
                        <td>{{ p.contractor_contract }}</td>
                        <td>{{ p.status }}</td>
                        <td>{{ p.advance_payment1 }}</td>
                        <td>{{ p.advance_payment2 }}</td>
                        <td>{{ p.advance_payment3 }}</td>
                        <td>{{ p.final_sum }}</td>
                        <td>{{ p.cs_upd }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        
        <table class="table">
            <thead class="thead-light">
            <tr>
                <th>Название</th>
                <th>Номер договора</th>
                <th>Бренд</th>
                <th>Подрядчик</th>
                <th>Номер договора с подрядчиком</th>
                <th>Статус проекта</th>
                <th>Аванс</th>
                <th>Аванс</th>
                <th>Аванс</th>
                <th>Итоговая сумма</th>
                <th>КС/УПД</th>
            </tr>
            </thead>
            <tbody>
            {% for p in projects %}
                {% if p.status == 'Закончен' %}
                    <tr>
                        <td><a href="{{ p.get_absolute_url }}" class="link-warning">{{ p.name }}</a></td>
                        <td>{{ p.contract_number }}</td>
                        <td>{{ p.brand }}</td>
                        <td>{{ p.contractor }}</td>
                        <td>{{ p.contractor_contract }}</td>
                        <td>{{ p.status }}</td>
                        <td>{{ p.advance_payment1 }}</td>
                        <td>{{ p.advance_payment2 }}</td>
                        <td>{{ p.advance_payment3 }}</td>
                        <td>{{ p.final_sum }}</td>
                        <td>{{ p.cs_upd }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
        
    <p class="text-right">
        <a href="{% url 'add_object:add_object' %}" class="btn btn-dark">Добавить проект</a>
    </p>
</div>

{% endblock %}

apps/core/templates/core/detail.html
{% extends 'base.html' %}
{% block title %}
{{ project.name }}
{% endblock %}
{% block content %}
<div class="container-fluid content">
    <button type="button" value="Previous Page" class="btn btn-dark" onClick="window.history.back();return false;" style="margin-left: 6%; margin-top: 3%;">
        Назад
    </button>
    <div class="col-md-6" style="margin-left: 25%; font-size: larger;">
        <h3>Название проекта: {{ project.name }}</h3>
        <p>Адрес: {{ project.adress }}</p>
        <p>Инженер: {{ project.engineer }}</p>
        <p>Контакты: {{ project.contacts }}</p>
        <p>Статус: {{ project.status }}</p>
        <p class="text-right">
            <a href="#" class="btn btn-dark">Изменить</a>
        </p>
    </div>
</div>
{% endblock %}

apps/core/templates/core/login.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="card">
<div class="card-body">
<h4 class="card-title">Log in to your account/n asdfghjfdsaa</h4>

<div>
    <div>
        <h2>Login</h2>
        
        <form method="post">
            <table>
                {{ form.as_p }}
                <tr>
                    <td>&nbsp;</td>
                    <td><input type="submit" value="Submit"></td>
                </tr>                
            </table>

        <button type="submit" class="btn btn-primary btn-block">Log in</button>
        </form>
    </div>
</div>

{% endblock %}